### PR TITLE
Polish: update app icons

### PR DESCRIPTION
**Pull request by alavren**

### CODE REVIEW

**Review by Tammerabi — APPROVED** [review]
Does this need a version bump? If we don't bump version will deploy fail? @tem-tem 
That's fine, if it doesn't impact the downloadable file. Not every PR merge should get a version anyway.

**Comment by alavren** [comment]
> Does this need a version bump? If we don't bump version will deploy fail? @tem-tem That's fine, if it doesn't impact the downloadable file. Not every PR merge should get a version anyway.

Idk, if there's no need to bump version and these icons can wait for larger changes to build new version I can remove that. Just thought that each merge should build new version.

**Comment by Tammerabi** [comment]
> > Does this need a version bump? If we don't bump version will deploy fail? @tem-tem That's fine, if it doesn't impact the downloadable file. Not every PR merge should get a version anyway.
> 
> Idk, if there's no need to bump version and these icons can wait for larger changes to build new version I can remove that. Just thought that each merge should build new version.

I guess if it's not urgent it shouldn't get a version bump, since we don't want people to have to update just for some minor thing that could've waited for a "release", you know? Also since we display all versions lol. But I guess it doesn't matter for now

**Comment by tem-tem** [comment]
@Tammerabi merging without version update will skip the packaging - take a look at this merge https://github.com/prometheon/bedrock-electron-2/actions/runs/5271201573
it didn't trigger new version release, but the code did end up in the main branch. We just have to keep in mind that, it's not a failed job, but a merge without release. Or we can have a "stage" that will collect new features for the next release.

**Comment by Tammerabi** [comment]
> @Tammerabi merging without version update will skip the packaging - take a look at this merge https://github.com/prometheon/bedrock-electron-2/actions/runs/5271201573 it didn't trigger new version release, but the code did end up in the main branch. We just have to keep in mind that, it's not a failed job, but a merge without release. Or we can have a "stage" that will collect new features for the next release.

Awesome, thank you

**Comment by alavren** [comment]
> @Tammerabi merging without version update will skip the packaging - take a look at this merge https://github.com/prometheon/bedrock-electron-2/actions/runs/5271201573 it didn't trigger new version release, but the code did end up in the main branch. We just have to keep in mind that, it's not a failed job, but a merge without release. Or we can have a "stage" that will collect new features for the next release.

Is there a way to skip version check job to merge it?

**Comment by Tammerabi** [comment]
> Is there a way to skip version check job to merge it?

Yeah I can do that 👍

**Pull request merged**
